version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=keycloak
    ports:
      - "5432:5432"
    networks:
      - keyCloakNetwork

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:10.0.2
    depends_on: 
      - postgres
    environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
    - DB_ADDR=postgres
    - DB_USER=root
    - DB_PASSWORD=root
    ports:
    - "8080:8080"
    - "8443:8443"
    networks:
      - keyCloakNetwork

networks:
  keyCloakNetwork: